/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DocTitle: (typeof import('./src/components/DocTitle.vue'))['default']
    DocPage: (typeof import('./src/components/DocPage.vue'))['default']
    HomeView: (typeof import('./src/views/HomeView.vue'))['default']
    Modules: (typeof import('./src/views/Modules.vue'))['default']
    NavBar: (typeof import('./src/components/NavBar.vue'))['default']
    NotFound: (typeof import('./src/views/NotFound.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    Snippet: (typeof import('./src/components/Snippet.vue'))['default']
    TopBar: (typeof import('./src/components/TopBar.vue'))['default']
  }
}
